FROM node:25-slim AS builder

WORKDIR /app

COPY package.json yarn.lock .

RUN yarn install

COPY . . 

RUN yarn build

FROM node@sha256:4b737db88848e949e50429a242d7010f6ef282b2178935a9f21dad805dae504b AS production

RUN adduser -u 1001 -D rihad

WORKDIR /app

COPY --from=builder /app/build ./build

RUN yarn global add serve

USER rihad

EXPOSE 3000

CMD ["serve", "-s", "build"]

