FROM node:25-slim AS builder

WORKDIR /app

COPY package.json yarn.lock .

RUN yarn install

COPY . . 

RUN yarn build

FROM node:25-alpine AS production

WORKDIR /app

COPY --from=builder /app/build ./build

RUN yarn global add serve

EXPOSE 3000

CMD ["serve", "-s", "build"]

